 # $Id: Makefile.linux_icc_sse2 1162 2013-05-27 16:48:11Z wrp $
#
# makefile for fasta3, fasta3_t using the Intel icc compiler
#
# This file is designed for 64-bit Linux systems.
# -D_LARGEFILE64_SOURCE and # -DBIG_LIB64 require a 64-bit linux system.
#
# uses SSE2 extensions for ssearch36(_t)

SHELL=/bin/bash

CC= icc -std=c99 -O3 -g -pthread
LIB_DB=
#CC = icc -g -DDEBUG
#LIB_DB=-lz

#CC=gcc -Wall -pedantic -ansi -g -O
#CC= /usr/local/parasoft/bin/insure -g -DDEBUG

# this file works for x86 LINUX

# standard options
CFLAGS= -D_POSIX_C_SOURCE=2 -DSHOW_HELP -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DMAX_WORKERS=8 -DTHR_EXIT=pthread_exit  -DUSE_MMAP -D_REENTRANT -DHAS_INTTYPES -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_FSEEKO -DPGM_DOC -DBIG_LIB64 -DSAMP_STATS
# -I/usr/include/mysql -DMYSQL_DB
#(for mySQL databases)  (also requires change to Makefile36.common)

LIB_M = -lm
#LIB_M = -L/usr/local/lib/mysql -lmysqlclient -lm
# for mySQL databases

HFLAGS=

# for Linux
THR_SUBS = pthr_subs2
THR_LIBS = -lpthread
THR_CC =

BIN = ../bin
XDIR = /seqprg/bin

# set up files for SSE2/Altivec acceleration
#
include ../make/Makefile.sse_alt

# no acceleration
#
DROPGSW_O = $(DROPGSW_SSE_O)
DROPLAL_O = $(DROPLAL_SSE_O)
DROPGNW_O = $(DROPGNW_SSE_O)
DROPLNW_O = $(DROPLNW_SSE_O)

# renamed (fasta36)  programs
include ../make/Makefile36m.common
# conventional (fasta3) names
# include ../make/Makefile.common

