# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
#
#  $Name:  $ - $Id: Makefile.os_x86_64 1228 2013-09-26 19:46:29Z wrp $
#
# 12-Dec-2007 - modified to allow compilation of both accelerated and
# non-accelerated Smith-Waterman

# the -DDEBUG option provides additional debugging information, particularly
# with -D on the command line.

# use -DBIG_LIB64 to generate 64-bit offsets in map_db .xin files

SHELL=/bin/bash

CC= cc -O -g -arch x86_64 -msse2
#CC= cc -g -DDEBUG -fsanitize=address -arch x86_64 -msse2

#CC= cc -g -Wall -pedantic
#
# standard line for normal searching
CFLAGS= -DSHOW_HELP -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DMAX_WORKERS=4 -DTHR_EXIT=pthread_exit  -DM10_CONS -DFASTA_HOST='"your.fasta.host.here"' -DIS_LITTLE_ENDIAN -DUSE_MMAP -DUSE_FSEEKO -DHAS_INTTYPES -DSAMP_STATS -DPGM_DOC -DBIG_LIB64 -DLIB_MEM=12

#-DSHOW_ALIGN_SCORE
# -I/usr/include/mysql -DMYSQL_DB  # add for MySQL support

LDFLAGS= -arch x86_64

HFLAGS= -o
NFLAGS= -o

#for Linux, MacOS, DEC Unix V4.0
THR_SUBS = pthr_subs2
THR_LIBS =
THR_CC =

BIN = ../bin
#XDIR = ${HOME}/bin
#XDIR = /home/slib/bin/MACOSX/
#XDIR = /Users/seqprg/bin
XDIR = /seqprg/bin
#XDIR = ./x86_64

# diectory for universal binary process
UDIR = $(BIN)/x86_64

# set up files for SSE2/Altivec acceleration
#
include ../make/Makefile.sse_alt

# Altivec acceleration
#
DROPGSW_O = $(DROPGSW_SSE_O)
DROPLAL_O = $(DROPLAL_SSE_O)
DROPGNW_O = $(DROPGNW_SSE_O)
DROPLNW_O = $(DROPLNW_SSE_O)

# provide mysql function
#include ../make/Makefile36m.common_mysql

# no mysql
include ../make/Makefile36m.common
