# $ Id: $
#
# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
#
# This file is designed for 32-bit Linux systems using an X86
# architecture without SSE2 extensions.
#
# To use on a 64-bit linux system, add -D_LARGEFILE64_SOURCE and -DBIG_LIB64
# (or use Makefile.linux64)
#

SHELL=/bin/bash

#CC= gcc -g -O
#CC = gcc -g -DDEBUG
#LIB_DB=

#CC=gcc -Wall -pedantic -ansi -g -O
CC= /usr/local/parasoft/bin/insure -g -DDEBUG
LIB_DB=-lz

# EBI uses the following with pgcc, -O3 does not work:
# CC= pgcc -O2 -pipe -mcpu=pentiumpro -march=pentiumpro -fomit-frame-pointer

# this file works for x86 LINUX

# standard options
CFLAGS= -DSHOW_HELP -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DMAX_WORKERS=4 -DTHR_EXIT=pthread_exit -DPROGRESS  -DUSE_MMAP -D_REENTRANT -DHAS_INTTYPES -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_FSEEKO -DSAMP_STATS -DPGM_DOC
# -DSFCHAR="'|'" -dSUPERFAMNUM

# -I/usr/local/include/mysql -DMYSQL_DB 
#
#(for mySQL databases)  (also requires change to Makefile35.common)

LIB_M = -lm
#LIB_M = -L/usr/local/lib/mysql -lmysqlclient -lm
# for mySQL databases

HFLAGS= -o
NFLAGS= -o

# for Linux
THR_SUBS = pthr_subs2
THR_LIBS = -lpthread
THR_CC =

BIN = ../bin
XDIR = /seqprg/bin

# set up files for SSE2/Altivec acceleration
#
include ../make/Makefile.sse_alt

# no acceleration
#
DROPGSW_O = $(DROPGSW_NA_O)
DROPLAL_O = $(DROPLAL_NA_O)
DROPGNW_O = $(DROPGNW_NA_O)
DROPLNW_O = $(DROPLNW_NA_O)

# renamed (fasta35)  programs
include ../make/Makefile36m.common
# conventional (fasta3) names
# include ../make/Makefile.common

