# $ Id: $
#
# makefile for fasta3, fasta3_t.  Use makefile.pvm for pvcompxx.
#
# Includes files for reading postgres (pgsql) databases
#
# This file is designed for 64-bit Linux systems.
# -D_LARGEFILE64_SOURCE and -DBIG_LIB64 require a 64-bit linux system.
# 

SHELL=/bin/bash

CC= gcc -g -O
LIB_DB=
#CC= gcc -g -DDEBUG
#LIB_DB=-lz
#CC=/opt/parasoft/bin.linux2/insure -g -DDEBUG

# this file works for x86 LINUX

# standard options
CFLAGS= -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DSFCHAR="':'" -DMAX_WORKERS=2 -DTHR_EXIT=pthread_exit  -DFASTA_HOST='"your_fasta_host_here"' -DUSE_MMAP -D_REENTRANT -I/usr/include/postgresql -DPGSQL_DB -D_FILE_OFFSET_BITS=64 -DUSE_FSEEKO -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DHAS_INTTYPES -DSAMP_STATS -DPGM_DOC -DM10_CONS -DBIG_LIB64

# use options below for superfamily validations
#CFLAGS= -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DSFCHAR="'|'" -DMAX_WORKERS=2 -DTHR_EXIT=pthread_exit -DPROGRESS -DSUPERFAMNUM -DUSE_MMAP -D_REENTRANT

# -I/usr/local/include/mysql -DMYSQL_DB 
#
#(for mySQL databases)  (also requires change to Makefile35.common)

#LIB_M = -lm
#LIB_M = -L/usr/lib/mysql -lmysqlclient -lm
# for mySQL databases

HFLAGS=

# for Linux
THR_SUBS = pthr_subs2
THR_LIBS = -lpthread
THR_CC =

BIN = ../bin
XDIR = /seqprg/bin

# set up files for SSE2/Altivec acceleration
#
include ../make/Makefile.sse_alt

# no acceleration
#
DROPGSW_O = $(DROPGSW_NA_O)
DROPLAL_O = $(DROPLAL_NA_O)
DROPGNW_O = $(DROPGNW_NA_O)
DROPLNW_O = $(DROPLNW_NA_O)

# renamed (fasta36)  programs
include ../make/Makefile36m.common_pgsql
# conventional (fasta3) names
# include ../make/Makefile.common
